// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/orders/orders_handler.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewOrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishName string `protobuf:"bytes,1,opt,name=dishName,proto3" json:"dishName,omitempty"`
	ItemId   int32  `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Comment  string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *NewOrderItem) Reset() {
	*x = NewOrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_orders_orders_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrderItem) ProtoMessage() {}

func (x *NewOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_orders_orders_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrderItem.ProtoReflect.Descriptor instead.
func (*NewOrderItem) Descriptor() ([]byte, []int) {
	return file_pkg_orders_orders_handler_proto_rawDescGZIP(), []int{0}
}

func (x *NewOrderItem) GetDishName() string {
	if x != nil {
		return x.DishName
	}
	return ""
}

func (x *NewOrderItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *NewOrderItem) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type PutNewOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int32           `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Items   []*NewOrderItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PutNewOrderRequest) Reset() {
	*x = PutNewOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_orders_orders_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutNewOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutNewOrderRequest) ProtoMessage() {}

func (x *PutNewOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_orders_orders_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutNewOrderRequest.ProtoReflect.Descriptor instead.
func (*PutNewOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_orders_orders_handler_proto_rawDescGZIP(), []int{1}
}

func (x *PutNewOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PutNewOrderRequest) GetItems() []*NewOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PutNewOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PutNewOrderResponse) Reset() {
	*x = PutNewOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_orders_orders_handler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutNewOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutNewOrderResponse) ProtoMessage() {}

func (x *PutNewOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_orders_orders_handler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutNewOrderResponse.ProtoReflect.Descriptor instead.
func (*PutNewOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_orders_orders_handler_proto_rawDescGZIP(), []int{2}
}

func (x *PutNewOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pkg_orders_orders_handler_proto protoreflect.FileDescriptor

var file_pkg_orders_orders_handler_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x22, 0x5c, 0x0a, 0x0c, 0x4e, 0x65,
	0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x4e,
	0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x50, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x62, 0x0a, 0x14, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0b,
	0x50, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x64, 0x6d, 0x62, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x32, 0x2d, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_orders_orders_handler_proto_rawDescOnce sync.Once
	file_pkg_orders_orders_handler_proto_rawDescData = file_pkg_orders_orders_handler_proto_rawDesc
)

func file_pkg_orders_orders_handler_proto_rawDescGZIP() []byte {
	file_pkg_orders_orders_handler_proto_rawDescOnce.Do(func() {
		file_pkg_orders_orders_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_orders_orders_handler_proto_rawDescData)
	})
	return file_pkg_orders_orders_handler_proto_rawDescData
}

var file_pkg_orders_orders_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_orders_orders_handler_proto_goTypes = []interface{}{
	(*NewOrderItem)(nil),        // 0: handler.NewOrderItem
	(*PutNewOrderRequest)(nil),  // 1: handler.PutNewOrderRequest
	(*PutNewOrderResponse)(nil), // 2: handler.PutNewOrderResponse
}
var file_pkg_orders_orders_handler_proto_depIdxs = []int32{
	0, // 0: handler.PutNewOrderRequest.items:type_name -> handler.NewOrderItem
	1, // 1: handler.KitchenOrdersHandler.PutNewOrder:input_type -> handler.PutNewOrderRequest
	2, // 2: handler.KitchenOrdersHandler.PutNewOrder:output_type -> handler.PutNewOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_orders_orders_handler_proto_init() }
func file_pkg_orders_orders_handler_proto_init() {
	if File_pkg_orders_orders_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_orders_orders_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_orders_orders_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutNewOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_orders_orders_handler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutNewOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_orders_orders_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_orders_orders_handler_proto_goTypes,
		DependencyIndexes: file_pkg_orders_orders_handler_proto_depIdxs,
		MessageInfos:      file_pkg_orders_orders_handler_proto_msgTypes,
	}.Build()
	File_pkg_orders_orders_handler_proto = out.File
	file_pkg_orders_orders_handler_proto_rawDesc = nil
	file_pkg_orders_orders_handler_proto_goTypes = nil
	file_pkg_orders_orders_handler_proto_depIdxs = nil
}
