// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/orders/orders_handler.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KitchenOrdersHandlerClient is the client API for KitchenOrdersHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KitchenOrdersHandlerClient interface {
	PutNewOrder(ctx context.Context, in *PutNewOrderRequest, opts ...grpc.CallOption) (*PutNewOrderResponse, error)
}

type kitchenOrdersHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewKitchenOrdersHandlerClient(cc grpc.ClientConnInterface) KitchenOrdersHandlerClient {
	return &kitchenOrdersHandlerClient{cc}
}

func (c *kitchenOrdersHandlerClient) PutNewOrder(ctx context.Context, in *PutNewOrderRequest, opts ...grpc.CallOption) (*PutNewOrderResponse, error) {
	out := new(PutNewOrderResponse)
	err := c.cc.Invoke(ctx, "/handler.KitchenOrdersHandler/PutNewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KitchenOrdersHandlerServer is the server API for KitchenOrdersHandler service.
// All implementations must embed UnimplementedKitchenOrdersHandlerServer
// for forward compatibility
type KitchenOrdersHandlerServer interface {
	PutNewOrder(context.Context, *PutNewOrderRequest) (*PutNewOrderResponse, error)
	mustEmbedUnimplementedKitchenOrdersHandlerServer()
}

// UnimplementedKitchenOrdersHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedKitchenOrdersHandlerServer struct {
}

func (UnimplementedKitchenOrdersHandlerServer) PutNewOrder(context.Context, *PutNewOrderRequest) (*PutNewOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutNewOrder not implemented")
}
func (UnimplementedKitchenOrdersHandlerServer) mustEmbedUnimplementedKitchenOrdersHandlerServer() {}

// UnsafeKitchenOrdersHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KitchenOrdersHandlerServer will
// result in compilation errors.
type UnsafeKitchenOrdersHandlerServer interface {
	mustEmbedUnimplementedKitchenOrdersHandlerServer()
}

func RegisterKitchenOrdersHandlerServer(s grpc.ServiceRegistrar, srv KitchenOrdersHandlerServer) {
	s.RegisterService(&KitchenOrdersHandler_ServiceDesc, srv)
}

func _KitchenOrdersHandler_PutNewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNewOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenOrdersHandlerServer).PutNewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handler.KitchenOrdersHandler/PutNewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenOrdersHandlerServer).PutNewOrder(ctx, req.(*PutNewOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KitchenOrdersHandler_ServiceDesc is the grpc.ServiceDesc for KitchenOrdersHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KitchenOrdersHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handler.KitchenOrdersHandler",
	HandlerType: (*KitchenOrdersHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutNewOrder",
			Handler:    _KitchenOrdersHandler_PutNewOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/orders/orders_handler.proto",
}
